config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  

  shallow do
    resources :users, only: %i(new show create index) do
      resources :days, only: %i(index create show destroy edit update) do
        resources :meals
      end
      resources :foods  
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :user
  has_many :meals

  validates :user_id, presence: true
  
  validates :protein, presence: true 
  validates :day, presence: true, uniqueness: { scope: :user_id, message: "Today was already created." }
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true

  validates :name, presence: true, :length => { :maximum => 30, 
    too_long: "Name can be up to 30 characters in length." }, 
    uniqueness: { message: "Food with such name exists." } 
  validates :description, presence: true, :length => { :maximum => 200 ,
    too_long: "desription can be up to 200 characters in length" }
  
  validates :energy, presence: true, numericality: { only_integer: true }
  validates :fat, presence: true, numericality: true
  validates :protein, presence: true, numericality: true
  validates :carbohydrate, presence: true, numericality: true
  validates :fibre, presence: true, numericality: true
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :day
  has_many :foods

  attr_reader :protein

  validates :day_id, presence: true
  validates :food_id, presence: true 
  validates :grams, presence: true, :length => { :maximum => 5000 ,
    too_long: "Grams can be up to 5 characters in length" }

  def self.meals(day)
    where(day_id: day.id)
  end

  def self.get_protein(day)
  	food = Food.find(day.food_id)
  	food.protein * day.grams / 100.0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :days
  has_many :foods

  has_secure_password
  #, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :email, presence: true, uniqueness: { message: "This email is already used." }
  validates :admin, presence: true
  
  def self.authenticate(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    return user if user.password == password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def create
    @day = Day.new
    @day.update(day: DateTime.now.to_date, user_id: params[:user_id]) 
    if @day.save 
      redirect_to user_days_path
    else
      flash[:error] = @day.errors   
      redirect_to user_days_path
    end
  end 

  def index
    @days = Day.where(user_id: params[:user_id])
  end

  def show
    @day = Day.find(params[:id])
    @meals = Meal.meals(@day)
  end

  def destroy
    @day = Day.find(params[:id])
    if @day.delete
      flash.now[:notice] = "The day was deleted successfully."
      redirect_to user_days_path(current_user)
    else
      flash.now[:error] = "The day was not deleted."
      redirect_to user_days_path(current_user)
    end
  end

  def edit
    @day = Day.find(params[:id])
  end

  def update
    meal = Meal.find(params[:id])
    @day = Day.find(meal.day_id)
    @day.protein = days_params[:protein]
    if @day.save
      redirect_to action: 'show'
    else
      redirect_to action: 'edit'
    end
  end

  def days_params
    params.require(:day).permit(:protein)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController 
  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = params[:user_id] 
    if @food.save
      flash[:notice] = "Food created successfully."
      redirect_to user_foods_path
    else
      flash.now[:error] = "Some error occured. The food was not created."
      render :new
    end
  end

  def index
    @foods = Food.where(user: current_user)
  end

  private

  def food_params
    params.require(:food).permit(:name, :description, :energy, :fat, :protein, :carbohydrate, :fibre)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.day_id = params[:day_id]

    if @meal.save
      day = Day.find(params[:day_id])
      day.protein += Meal.get_protein(@meal)
      if day.save
        flash.now[:notice] = "successfully increased day's protein"
      else 
        flash.now[:error] = "could not increase day's protein"
      end
        redirect_to day_path(params[:day_id])
    else
      flash.now[:error] = "Meal was not created."
      render :new
    end
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def edit
    @meal = Meal.find(params[:id])  
  end
  
  def update
    @meal = Meal.find(params[:id])
    day = Day.find(@meal.day_id)
    old_meals_protein = Meal.get_protein(@meal)
    
    @meal.grams = params[:meal][:grams]
    @meal.description = params[:meal][:description]
    @meal.food_id = params[:meal][:food_id]

    if @meal.save
      day.protein -= old_meals_protein
      day.protein += Meal.get_protein(@meal)
      #TODO Day#update_protein
      if day.save
        flash.now[:notice] = "successfully increased day's protein"
      else 
        flash.now[:error] = "could not increase day's protein"
      end

      flash.now[:notice] = "edit successful, protein is refreshed"
      redirect_to action: 'show'
    else
      flash.now[:error] = "could not edit the meal"
      redirect_to action: 'edit'
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    day = Day.find(@meal.day_id)
    day.protein -= Meal.get_protein(@meal)
    if @meal.delete
      if day.save
        flash.now[:notice] = "successfully decreased day's protein"
      else 
        flash.now[:error] = "could decrease day's protein"
      end

      flash.now[:notice] = "The meal was deleted successfully."
      redirect_to day_path(@meal.day_id)
    else
      flash.now[:error] = "The meal was not deleted."
      redirect_to day_meals_path(@meal.day_id)
    end
  end

  private

  def meal_params
    params.require(:meal).permit(:grams, :description, :food_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create  
    @user = User.find_by(email: params[:session][:email])
    if @user and @user.authenticate(params[:session][:password])
      sign_in @user
      redirect_to @user, notice: "Successfully logged in"
    else
      flash.now[:error] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    sign_out
    flash.now[:notice] = "Successfully logged out"
    render :new 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    #@user = User.new(email:"test", password:"test")

    if @user.save
      sign_in(@user)
      UserMailer.welcome_mail(@user).deliver_later
      flash[:notice] = "User created successfully."
      render :show
    else
      flash[:error] = "Some error occured. The user was not creted."
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end
  
  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id]) 
    else
      deny_acces
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def deny_acces
    redirect_to '/login', flash[:notice] = "Please sign in to access this page"
  end
end

app/views/days/_day.html.erb
<div class='col-sm-6 col-lg-4' >
	<div class="card">
		<div class="card-topper" style='background-image: url(http://lolofit.com/assets/icons/go_icon_large-aef28c5b2903df8f238044f0a1615eb5e7d4148a6b286e8895d18a0a490df746.png);'></div>
		<div class="card-block">
			<h4 class="card-day">Date : <%= link_to day.day, day %></h4>
			<p class="card-protein">Protein : <%= link_to day.protein, day %></p>
			<%= link_to 'Back to user', user_path(params[:user_id]), class: 'btn btn-user' %>

		</div>
	</div>
</div>

app/views/days/edit.html.erb
<%= flash[:error] if flash[:error] %>
<%= flash[:notice] if flash[:notice] %>

<%= form_for @day, method: :patch, url: 
	day_path(@day) do |f| %>
  <%= f.label :protein %></br>
  <%= f.text_field :protein %></br>

  <%= f.submit %>
<% end %>

app/views/days/index.html.erb
<% provide(:days_active, "active") %>
<% provide(:page_title, "Days") %>

<%= flash[:error] if flash[:error] %>
<%= flash[:notice] if flash[:notice] %>


<div class="row">
    <% @days.each do |day| %>
        <%= render day %>
    <% end %> 
</div>

<%= link_to 'Back to user', user_path(params[:user_id]) %>
<%=  link_to 'New day',{:action => :create}, :method => :post, :user_id => params[:user_id] %>

app/views/days/show.html.erb
<% provide(:page_title, "Day #{@day.id}") %>
<%= flash[:error] if flash[:error] %>
<%= flash[:notice] if flash[:notice] %>
<%= @day.inspect %>

<table>
	<tr>
		<th>food</th>
		<th>grams</th>
		<th colspan="3">Options</th>
	</tr>

	<tbody>
    <% if @meals.empty? %>
      <strong> No meals yet</strong>
    <% else %>
    	<% @meals.each do |meal| %>
    		<tr>
    			<td><%= Food.find(meal.food_id).name %></td>
    			<td><%= meal.grams %></td>
                <td><%= link_to 'Show meal', meal_path(meal.id) %></td>
                <td><%= link_to 'Edit meal', edit_meal_path(meal.id) %></td>
                <td><%= link_to 'Delete meal', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    		</tr>
    	<% end %>
		<% end %>
	</tbody>
</table>

<%= link_to 'Add meal', new_day_meal_path(@day) %>
<%= link_to 'Back to Days', user_days_path(current_user) %>	

app/views/foods/index.html.erb
<%= @foods.inspect %>

<%= link_to 'Back to user', user_path(params[:user_id]) %>
<%= link_to 'Add new food', new_user_food_path %>

app/views/foods/new.html.erb
<%= @food.errors.messages if flash[:error] %>
<%= flash[:error] if flash[:error] %>

<p>New food</p>

<%= form_for @food, :url => user_foods_path do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.label :energy %>
	<%= f.text_field :energy %>
	<%= f.label :fat %>
	<%= f.text_field :fat %>
	<%= f.label :protein %>
	<%= f.text_field :protein %>
	<%= f.label :carbohydrate %>
	<%= f.text_field :carbohydrate %>
	<%= f.label :fibre %>
	<%= f.text_field :fibre %>

	<%= f.submit 'Create food'%>
<% end %>

<%= link_to 'Back to user', user_path(params[:user_id]) %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Training Buddy</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= yield(:home_active)%>"><%= link_to "Home", root_path %></li>
        <li class="<%= yield(:user_active)%>"><%= link_to "User", user_path(current_user) %></li>
        <li class="<%= yield(:days_active)%>"><%= link_to "Days", user_days_path(current_user) %></li>
      </ul> 
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | TrainingBuddy</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>"> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/meals/edit.html.erb
<% provide(:page_title, "Edit Meal") %>

<%= form_for @meal, method: :patch, url: 
	meal_path(@meal) do |f| %>
 	<%= f.label :grams %>
	<%= f.text_field :grams %>
	<%= f.label :food_id %>
	<%= f.collection_select :food_id, Food.order(:name),:id,:name, include_blank: true %>
	<%= f.label :description %>
	<%= f.text_area :description %>

  <%= f.submit %>
<% end %>

<%= flash[:error] if flash[:error] %>
<%= flash[:notice] if flash[:notice] %>

app/views/meals/index.html.erb
<%= flash[:error] if flash[:error] %>
<%= flash[:notice] if flash[:notice] %>

<table>
	<tr>
		<th>food</th>
		<th>grams</th>
		<th colspan="4">Options</th>
	</tr>

	<tbody>
    <% if @meals.empty? %>
      <strong> No meals yet</strong>
    <% else %>
    	<% @meals.each do |meals| %>
    		<tr>
    			<td><%= meals.food_id %></td>
    			<td><%= meals.grams %></td>
                <td><%= link_to 'View meal', meal_path(meals.id) %></td>
                <td><%= link_to 'Back to day', day_path(params[:day_id]) %></td>
                <td><%= link_to 'Back to user', user_path(current_user) %></td>
                <td><%= link_to 'Delete meals', meals,  method: :delete, data: { confirm: 'Are you sure?' } %></td>
    		</tr>
    	<% end %>
		<% end %>
	</tbody>
</table>
 

app/views/meals/new.html.erb
<% provide(:page_title, "New meal") %>
<%= flash[:error] if flash[:error] %>

<p>New meal</p>

<%= form_for @meal, :url => day_meals_path do |f| %>
	<%= f.label :grams %>
	<%= f.text_field :grams %>
	<%= f.label :food_id %>
	<%= f.collection_select :food_id, Food.order(:name),:id,:name, include_blank: true %>
	<%= f.label :description %>
	<%= f.text_area :description %>

	<%= f.submit 'Add meal'%>
<% end %>

<%= link_to 'Back to user', user_path(current_user) %>
<%= link_to 'Add product', new_user_food_path(current_user) %>

app/views/meals/show.html.erb
<%= flash[:notice] if flash[:notice] %>
<%= flash[:error] if flash[:error] %>

<%= @meal.inspect %>

<%= link_to 'Back to meals of this day', day_path(@meal.day_id) %>
<%= link_to 'Back to days', user_days_path(current_user) %>

app/views/users/index.html.erb
<table>
	<tr>
		<th>id</th>
		<th>email</th>
		<th>craeted at</th>
	</tr>

	<tbody>
    <% if @users.empty? %>
      <strong> No users yet</strong>
    <% else %>
    	<% @users.each do |user| %>
    		<tr>
    			<td><%= user.id %></td>
    			<td><%= user.email %></td>
    			<td><%= user.created_at %></td>
          <td></td>
    		</tr>
    	<% end %>
		<% end %>
	</tbody>
</table>

app/views/users/new.html.erb
<%= flash[:error] if flash[:error] %>

<p>New user</p>

<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.submit 'Create user'%>
<% end %>

app/views/users/show.html.erb
<% provide(:user_active, "active") %>

<%= flash[:notice] if flash[:notice] %>
<%= flash[:error] if flash[:error] %>
<% provide(:page_title, @user.email) %>

<p>Hello, <%= @user.email %>!</p>

<%= @user.inspect %>


<%= link_to 'Days', user_days_path(@user) %>
<%= link_to 'Log out', '/logout' %>